version: '2.1'
services:

  db:
    container_name: continuousdelivery_db
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    ports:
      - "${DB_PORT}:3306"
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 30s
        timeout: 10s
        retries: 5

  ngspring:
    container_name: continuousdelivery_demo
    image: continuous-delivery/demo
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

